### ISSUE TITLE
0.9rc14 : get_database_list InfluxDBClientError

### ISSUE THREAD

**Issue by steverweber** [influxdb/influxdb-python#129]
influxdb 0.9rc14

```
pip list | grep influxdb
influxdb (1.x)

...
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1562, in call                                    
                  **cdata['kwargs'])                                                                                         
                File "/usr/lib/python2.7/dist-packages/salt/states/influxdb_user.py", line 47, in present                    
                  database, user, password, host, port):                                                                     
                File "/usr/lib/python2.7/dist-packages/salt/modules/influx.py", line 115, in db_exists                       
                  dbs = db_list(user, password, host, port)                                                                  
                File "/usr/lib/python2.7/dist-packages/salt/modules/influx.py", line 86, in db_list                          
                  return client.get_database_list()                                                                          
              AttributeError: 'InfluxDBClient' object has no attribute 'get_database_list'                                   
     Started: 20:23:22.023236

```

**Comment by steverweber** [comment]
ah nm, using old client.
InfluxDBClient

**Comment by steverweber** [comment]
err umm not using the old client.

**Comment by steverweber** [comment]
https://github.com/saltstack/salt/blob/develop/salt/modules/influx.py

**Comment by ReAzem** [comment]
What vesion of the inflxudb module are you using?

**Comment by steverweber** [comment]
yap wrong version.  sorry about the ??
this is closed!

**Comment by steverweber** [comment]
i forgot to:
```
pip install --upgrade influxdb
```
was running 0.4.1

**Comment by ReAzem** [comment]
You were very fast! I pushed to pypi minutes ago :)

**Comment by steverweber** [comment]
might have one issue...
```
get_database_list
```
has been renamed to c.get_list_database()

**Comment by steverweber** [comment]
kinda wonder why the function names changed... this will cause some disruption...

**Comment by ReAzem** [comment]
See #96. There will be alot of disruption since InfluxDB's API completely changed.

**Comment by steverweber** [comment]
man i was so confused.
its all good upstream already changed to get_list_database.. 
https://github.com/saltstack/salt/commit/b8deab5af9ee9f7253dbe1b62ce5d36012ea831d
