### ISSUE TITLE
JSON unmarshalling error

### ISSUE THREAD

**Issue by ramitha11** [influxdb/influxdb-python#186]
```
Traceback (most recent call last):
  File ".\one.py", line 22, in <module>
    client.write_points(json_body)
  File "C:\Python27\lib\site-packages\influxdb\client.py", line 364, in write_points
    tags=tags)
  File "C:\Python27\lib\site-packages\influxdb\client.py", line 406, in _write_points
    expected_response_code=204
  File "C:\Python27\lib\site-packages\influxdb\client.py", line 277, in write
    expected_response_code=expected_response_code
  File "C:\Python27\lib\site-packages\influxdb\client.py", line 257, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.client.InfluxDBClientError: 500: {"error":"json: cannot unmarshal object into Go value of type []client.Point"}
```

Getting this error while trying to ```write_points``` in localhost influxdb using InfluxDB Python API.

When I execute the JSON manually in the web UI, I am able to write the points in the DB correctly but while doing it with python code the above mentioned error is encountered

```
from influxdb import InfluxDBClient
json_body = {
    "database": "mydb1",
    "retentionPolicy": "default",
    "points": [
        {
            "name": "cpu_load_short",
            "tags": {
                "host": "server01",
                "region": "us-west"
            },
            "time": "2009-11-10T23:00:00Z",
            "fields": {
                "value": 0.64,
                "goal" : "love"
            }
        }
    ]
}
client = InfluxDBClient('localhost', 8086, 'root', 'mydb1')
client.create_database('mydb1')
client.write_points(json_body)
```

**Comment by georgijd** [comment]
Hi,

The reason why the operation is unsuccessful is because you're trying to write your data with the wrong method. If you construct your body like you do with the `json_body` variable, you should be using the `write` method, instead of `write_points`. However, if you want to use the `write_points` method, you could do something like this:
```
points = [{
    'name': 'cpu_load_short',
    'tags': {'host': 'server01', 'region': 'us-west'},
    'time': '2009-11-10T23:00:00Z',
    'fields': {'value': 0.64, 'goal': 'love'},
    }]
client.write_points(points=points, database='mydb1', retention_policy='default')
```

**Comment by aviau** [comment]
This is exact.
