### ISSUE TITLE
writing an integer field produces a 400 'invalid number' error

### ISSUE THREAD

**Issue by Nuclearfossil** [influxdb/influxdb-python#239]
Latest code drop, InfluxDB 9.2

Here's the code sample that produces the error:

```
    auditDBHost = settings['global']['auditdbhost']
    auditDBPort = settings['global']['auditdbport']
    auditDB = settings['global']['auditdb']

    nb_day = 1  # number of day to generate time series
    timeinterval_min = 50  # create an event every x minutes
    total_minutes = 1440 * nb_day
    total_records = int(total_minutes / timeinterval_min)
    #now = datetime.datetime.today()
    series = []

    # let's periodically write some random data into the DB for testing
    random.seed(time.time)

    for i in range(0, total_records):
        byteswritten = random.randint(100, 10000)
        metric = random.choice(["5150.bucket.category01",
                                "5150.bucket.category02",
                                "5150.bucket.category03",
                                "5150.bucket.category04",
                                "5150.bucket.category05",
                                "5150.bucket.category06"])
        titleID = metric.partition(".")[0]
        bucket = (metric.partition(".")[2]).partition(".")[0]
        category = (metric.partition(".")[2]).partition(".")[2]

        current_time = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
        pointValues = {
                "time": current_time,
                "measurement": '{0}'.format(metric),
                'fields':  {
                    'byteswritten': byteswritten,
                },
            "tags": {
                "titleID": titleID,
                "bucket": bucket,
                "category": category
            },
            }
        series.append(pointValues)
    print series

    client = InfluxDBClient(host=auditDBHost, port=auditDBPort, database=auditDB)

    print("Create database: " + auditDB)
    try:
        client.create_database(auditDB)
    except InfluxDBClientError:
        # Drop and create
        client.drop_database(auditDB)
        client.create_database(auditDB)

    print("Write points #: {0}".format(total_records))
    client.write_points(series)

    time.sleep(2)

    query = 'SELECT MEAN(byteswritten) FROM "{0}" WHERE time > now() - 10d GROUP BY time(500m)'.format(metric)
    result = client.query(query, database=auditDB)
    print (result)
    print("Result: {0}".format(result))
```
Based on the samples provided. The callstack looks like:

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 106, in exec_file
    exec_code(code, file, global_variables)
  File "C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\Extensions\Microsoft\Python Tools for Visual Studio\2.1\visualstudio_py_util.py", line 82, in exec_code
    exec(code_obj, global_variables)
  File "C:\Code\sdk\Evaluator\Evaluator\datapusher.py", line 100, in <module>
    main()
  File "C:\Code\sdk\Evaluator\Evaluator\datapusher.py", line 73, in main
    client.write_points(series)
  File "C:\Python27\lib\site-packages\influxdb-2.9.1-py2.7.egg\influxdb\client.py", line 383, in write_points
    tags=tags)
  File "C:\Python27\lib\site-packages\influxdb-2.9.1-py2.7.egg\influxdb\client.py", line 428, in _write_points
    expected_response_code=204
  File "C:\Python27\lib\site-packages\influxdb-2.9.1-py2.7.egg\influxdb\client.py", line 273, in write
    headers=headers
  File "C:\Python27\lib\site-packages\influxdb-2.9.1-py2.7.egg\influxdb\client.py", line 243, in request
    raise InfluxDBClientError(response.content, response.status_code)
InfluxDBClientError: 400: unable to parse '5311.bucket.category05,bucket=bucket,
category=category05,titleID=5150 byteswritten=1228i 1441238771000000000': invalid number
```
Are we looking at the additional 'i' at the end of the byteswritten? I've converted that to a float and it works fine. I find that hard to believe as I would expect that to be a standard test case.

**Comment by brettdh** [comment]
InfluxDB 0.9.3 introduced breaking changes, including the requirement that integers be written in the line protocol with a trailing `i`. Version 2.9.0 of the python client was updated to comply with this, so it won't work with InfluxDB 0.9.2.

I suppose the real issue here is that there's no obvious way to tell which versions of influxdb-python work with which versions of InfluxDB, and that (AFAICT) the CI setup just runs with the latest version.

**Comment by Nuclearfossil** [comment]
OK, easy enough to upgrade, as this is an new project, but you are correct - with no way to tell what the underlying InfluxDB you're talking to is going to be a significant issue.

**Comment by Nuclearfossil** [comment]
The other issue is that the installation page: https://influxdb.com/docs/v0.9/introduction/installation.html documents installing 9.2 and the downloads page https://influxdb.com/download/index.html points to 9.3.

Guess which one I was using?
