### ISSUE TITLE
Error running pandas example

### ISSUE THREAD

**Issue by muxspace** [influxdb/influxdb-python#246]
Hi, I'm running the [pandas example](http://influxdb-python.readthedocs.org/en/latest/examples.html) and am getting the following error:
```
>>> df = pd.DataFrame(data=list(range(30)),
...                       index=pd.date_range(start='2014-11-16',
...                                           periods=30, freq='H'))
>>> client.write_points(df,'example')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/panoptez/b-panoptez-env/local/lib/python2.7/site-packages/influxdb/_dataframe_client.py", line 68, in write_points
    points, time_precision, database, retention_policy)
  File "/opt/panoptez/b-panoptez-env/local/lib/python2.7/site-packages/influxdb/client.py", line 383, in write_points
    tags=tags)
  File "/opt/panoptez/b-panoptez-env/local/lib/python2.7/site-packages/influxdb/client.py", line 428, in _write_points
    expected_response_code=204
  File "/opt/panoptez/b-panoptez-env/local/lib/python2.7/site-packages/influxdb/client.py", line 273, in write
    headers=headers
  File "/opt/panoptez/b-panoptez-env/local/lib/python2.7/site-packages/influxdb/client.py", line 243, in request
    raise InfluxDBClientError(response.content, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: unable to parse 'example 0=0i 1416096000000000000': invalid number
```

I'm using influxdb-2.9.1 with InfluxDB shell 0.9.2 on Python 2.7.6 on Ubuntu 15.04. My guess is that it has something to do with 64 bit numbers, but I'm new to InfluxDB, so I wouldn't really know.

**Comment by brettdh** [comment]
Haven't dug deeply into this, but here's my guess: 

influxdb-python >=2.9.0 formats integers according to the line protocol in InfluxDB 0.9.3, which requires integers be suffixed with `i` (as seen in the error message you posted). You'll need to use influxdb-python < 2.9.0 or upgrade InfluxDB to 0.9.3 or higher.

**Comment by muxspace** [comment]
Awesome, that fixed it! Thanks much.
