### ISSUE TITLE
InfluxDBClientError: 404: {"error":"database not found: \"newdatabase\""}

### ISSUE THREAD

**Issue by prashleo** [influxdb/influxdb-python#273]
Hi,
 I am facing an error while writing the data into influxDB.
the irony is this doesn't happen for all the writes, and the newdatabase database  exists in the influxDB database

inflixdb-python version I am using is __version__ = '2.6.0'

Traceback (most recent call last):
  File "/opt/ampli/apps/marvinweb/venv/lib/python2.7/site-packages/marvin_libs-0.69.0-py2.7.egg/marvin_lib/network/savetoinfluxdb.py", line 420, in save_to_database
    response = influxdb_client.write_points(influxdb_data, time_precision)
  File "/opt/ampli/apps/marvinweb/venv/lib/python2.7/site-packages/influxdb/client.py", line 797, in func
    raise e
InfluxDBClientError: 404: {"error":"database not found: \"newdatabase\""}

**Comment by prashleo** [comment]
This is a dulicate of the issue https://github.com/influxdb/influxdb/issues/4170.

upgraded to the latest version 0.9.6.1 and I no loger see the issue.

closing this
